#ifndef MP3SPLT_VERSION_H

#define LIBMP3SPLT_MAJOR_VERSION 2
#define LIBMP3SPLT_MINOR_VERSION 8
#define LIBMP3SPLT_MICRO_VERSION 4

#define SPLT_PACKAGE_VERSION "2.8.4"

#define MP3SPLT_VERSION_H
#endif

